# Generated by Django 6.0.2 on 2026-02-27 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlerLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(db_index=True, max_length=50)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('retry_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Custo Médio')),
                ('sale_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Preço Venda')),
                ('total_quantity', models.IntegerField(default=0)),
                ('min_quantity', models.IntegerField(default=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Produto')),
                ('bar_code', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código de Barras')),
                ('natura_sku', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='SKU Natura')),
                ('category', models.CharField(default='Geral', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('min_quantity', models.PositiveIntegerField(default=5)),
                ('official_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Preço Site')),
                ('last_checked_price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True, verbose_name='Última Checagem de Preço')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('VENDA', 'Venda'), ('PRESENTE', 'Presente Pessoal'), ('BRINDE', 'Brinde Cliente'), ('PERDA', 'Perda/Avaria'), ('USO_PROPRIO', 'Uso Próprio')], default='VENDA', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('client_name', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_method', models.CharField(blank=True, default='DINHEIRO', max_length=50)),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('batch_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Lote')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Validade')),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='inventory.inventoryitem')),
            ],
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Coletado')),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='inventory.product')),
            ],
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product'),
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('unit_price_sold', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_cost_at_time', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventorybatch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.sale')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Minha Loja Natura', max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='store', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='sale',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='inventory.store'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.store'),
        ),
        migrations.AlterUniqueTogether(
            name='inventoryitem',
            unique_together={('store', 'product')},
        ),
    ]
