# Generated by Django 6.0.2 on 2026-03-20 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='store',
            name='payment_external_id',
            field=models.CharField(blank=True, help_text='ID da transação/assinatura', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='payment_provider',
            field=models.CharField(blank=True, help_text='Ex: stripe, mercadopago', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='plan',
            field=models.CharField(choices=[('free', 'Free'), ('pro', 'Pro')], default='pro', help_text='Plano de assinatura da loja', max_length=20),
        ),
        migrations.AddField(
            model_name='store',
            name='storefront_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='store',
            name='subscription_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='subscription_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
