# Generated by Django 6.0.2 on 2026-04-06 02:17

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_registrationsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('premium', 'Premium')], max_length=20, unique=True)),
                ('display_name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('max_products', models.IntegerField(blank=True, help_text='NULL = ilimitado', null=True)),
                ('max_storage_mb', models.IntegerField(default=100)),
                ('can_use_scanner', models.BooleanField(default=True)),
                ('can_use_storefront', models.BooleanField(default=False)),
                ('can_use_alerts', models.BooleanField(default=False)),
                ('can_use_ai_assistant', models.BooleanField(default=False)),
                ('can_use_analytics', models.BooleanField(default=False)),
                ('can_export_data', models.BooleanField(default=False)),
                ('can_use_api', models.BooleanField(default=False)),
                ('monthly_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('yearly_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('yearly_discount_percent', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('highlight_color', models.CharField(default='#3B82F6', max_length=7)),
                ('is_popular', models.BooleanField(default=False)),
                ('is_visible', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração de Plano',
                'verbose_name_plural': 'Configurações de Planos',
                'db_table': 'plan_configs',
                'ordering': ['sort_order', 'plan_type'],
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('promotion_type', models.CharField(choices=[('banner', 'Banner'), ('modal', 'Modal'), ('notification', 'Notificação'), ('email', 'Email')], default='banner', max_length=20)),
                ('target_audience', models.CharField(choices=[('all', 'Todos os usuários'), ('free', 'Apenas plano Free'), ('pro', 'Apenas plano Pro'), ('new_users', 'Usuários novos (< 7 dias)'), ('inactive', 'Usuários inativos (> 30 dias)')], default='free', max_length=20)),
                ('discount_percent', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('max_views', models.IntegerField(blank=True, null=True)),
                ('current_views', models.IntegerField(default=0)),
                ('background_color', models.CharField(default='#3B82F6', max_length=7)),
                ('text_color', models.CharField(default='#FFFFFF', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Promoção',
                'verbose_name_plural': 'Promoções',
                'db_table': 'promotions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameField(
            model_name='store',
            old_name='user',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='store',
            name='storefront_enabled',
        ),
        migrations.AddField(
            model_name='store',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(default='Minha Loja Natura', max_length=255),
        ),
        migrations.AlterField(
            model_name='store',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
        migrations.CreateModel(
            name='UserPlanCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_plan', models.CharField(default='free', max_length=20)),
                ('max_products', models.IntegerField(blank=True, null=True)),
                ('products_used', models.IntegerField(default=0)),
                ('can_use_scanner', models.BooleanField(default=True)),
                ('can_use_storefront', models.BooleanField(default=False)),
                ('can_use_alerts', models.BooleanField(default=False)),
                ('can_use_ai_assistant', models.BooleanField(default=False)),
                ('can_use_analytics', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plan_cache', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cache de Plano',
                'verbose_name_plural': 'Cache de Planos',
                'db_table': 'user_plan_cache',
            },
        ),
    ]
