# Generated by Django 6.0.2 on 2026-04-09 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_planconfig_promotion_rename_user_store_owner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalBarcodeCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(db_index=True, max_length=100)),
                ('gtin', models.CharField(db_index=True, max_length=14, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('source', models.CharField(default='bluesoft', max_length=50)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('matched', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'external_barcode_catalog',
                'indexes': [models.Index(fields=['brand', 'matched'], name='external_ba_brand_e720d3_idx'), models.Index(fields=['source', 'created_at'], name='external_ba_source_5757d7_idx')],
            },
        ),
        migrations.CreateModel(
            name='MLInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(choices=[('conversion_prediction', 'Predição de Conversão'), ('churn_risk', 'Risco de Churn'), ('product_recommendation', 'Recomendação de Produto'), ('optimal_pricing', 'Precificação Otimizada'), ('seasonal_trend', 'Tendência Sazonal')], max_length=30)),
                ('target_segment', models.CharField(max_length=50)),
                ('confidence_score', models.FloatField()),
                ('insight_data', models.JSONField()),
                ('model_version', models.CharField(default='v1.0', max_length=20)),
                ('training_data_size', models.IntegerField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'ml_insights',
                'indexes': [models.Index(fields=['insight_type', 'target_segment'], name='ml_insights_insight_368b60_idx'), models.Index(fields=['generated_at'], name='ml_insights_generat_67fd30_idx')],
            },
        ),
        migrations.CreateModel(
            name='DataPrivacyConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_type', models.CharField(choices=[('analytics', 'Analytics e Métricas'), ('ml_training', 'Treinamento de IA'), ('personalization', 'Personalização'), ('marketing', 'Marketing Direcionado')], max_length=20)),
                ('granted', models.BooleanField(default=False)),
                ('granted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('consent_version', models.CharField(default='1.0', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_consents', to='inventory.store')),
            ],
            options={
                'db_table': 'data_privacy_consents',
                'unique_together': {('store', 'consent_type')},
            },
        ),
        migrations.CreateModel(
            name='UserBehaviorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('product_scan', 'Produto Escaneado'), ('product_add', 'Produto Adicionado'), ('product_edit', 'Produto Editado'), ('stock_update', 'Estoque Atualizado'), ('sale_record', 'Venda Registrada'), ('report_view', 'Relatório Visualizado'), ('storefront_access', 'Vitrine Acessada'), ('plan_view', 'Página de Planos Visualizada')], max_length=20)),
                ('plan_at_time', models.CharField(max_length=10)),
                ('products_count_at_time', models.IntegerField()),
                ('day_of_week', models.IntegerField()),
                ('hour_of_day', models.IntegerField()),
                ('session_duration_minutes', models.IntegerField(blank=True, null=True)),
                ('feature_used', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_logs', to='inventory.store')),
            ],
            options={
                'db_table': 'user_behavior_logs',
                'indexes': [models.Index(fields=['action_type', 'plan_at_time'], name='user_behavi_action__c79fb6_idx'), models.Index(fields=['created_at'], name='user_behavi_created_122497_idx'), models.Index(fields=['store', 'action_type'], name='user_behavi_store_i_4693a4_idx')],
            },
        ),
    ]
