# Generated by Django 6.0.2 on 2026-04-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_externalbarcodecatalog_mlinsight_dataprivacyconsent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalbarcodecatalog',
            name='confidence_level',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='externalbarcodecatalog',
            name='search_term_used',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='externalbarcodecatalog',
            name='searched_product_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='externalbarcodecatalog',
            name='searched_product_sku',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='externalbarcodecatalog',
            index=models.Index(fields=['searched_product_sku'], name='external_ba_searche_f613ee_idx'),
        ),
    ]
