"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
from urllib.parse import quote_plus
import os
from dotenv import load_dotenv
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")  # Garanta o caminho correto do .env

# Carrega variáveis
# Tenta carregar do .env, mas usa valores FIXOS corretos se falhar (Fallback)
DB_NAME = os.getenv("DB_NAME", "natura_inventory")
DB_USER = os.getenv("DB_USER", "natura_admin")       # <== Mude para seu usuário real
DB_PASSWORD = os.getenv("DB_PASSWORD", "senha_segura_123") # <== Use a senha que definiu no psql
DB_HOST = os.getenv("DB_HOST", "localhost")
DB_PORT = os.getenv("DB_PORT", "5432")
# Usuário de leitura da IA (se existir no .env)
DB_AI_USER = os.getenv("DB_AI_USER", "natura_ai")
DB_AI_PASSWORD = os.getenv("DB_AI_PASSWORD", "leitura_segura")

# Sanitização (quote_plus remove caracteres problemáticos como @, ç, espaços)
safe_ai_user = quote_plus(DB_AI_USER)
safe_ai_pass = quote_plus(DB_AI_PASSWORD)
safe_db_name = quote_plus(DB_NAME)
safe_host = quote_plus(DB_HOST)

# Monta a URL sanitizada para o LangChain
DATABASE_URL = f"postgresql+psycopg2://{safe_ai_user}:{safe_ai_pass}@{safe_host}:{DB_PORT}/{safe_db_name}"

# Configuração padrão do Django (não afeta o LangChain, mas bom manter igual)
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": DB_NAME,
        "USER": DB_USER,
        "PASSWORD": DB_PASSWORD,
        "HOST": DB_HOST,
        "PORT": DB_PORT,
    }
}


#print("ENV_PATH:", ENV_PATH)
#print("EXISTS:", ENV_PATH.exists())
#print("DB_NAME_env:", os.getenv("DB_NAME"))
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-+rc4szhd0d(k@((%vp6og@k_p)y5x*$9_=214d4+p@e3^o4gj7'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

        # Apps do projeto
    'inventory',
    'ai',

    # 🔹 Django REST Framework
   "corsheaders",
    "rest_framework",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware', # Deve vir antes do CommonMiddleware
    'django.middleware.common.CommonMiddleware',
    
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:5173", # Vite padrão
    "http://192.168.1.15:3000", # <--- Adicione seu IP aqui
    "http://192.168.1.15:8000",
]

CORS_ALLOW_ALL_ORIGINS = True
WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases



# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/
# Internacionalização
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'America/Sao_Paulo'
USE_I18N = True
USE_TZ = True

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
