"""
Django settings for core project.
Generated by 'django-admin startproject' using Django 6.0.2.
"""
import os
import json
import re
from urllib.parse import quote_plus
from pathlib import Path
from dotenv import load_dotenv
import dj_database_url
from cryptography.fernet import Fernet
from datetime import timedelta

# --------------------------------------------------------------------------
# Caminhos base / .env
# --------------------------------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(os.path.join(BASE_DIR, ".env"))

# Carrega chave Fernet (mantendo sua lógica existente)
env_key_path = BASE_DIR / ".env.key"
fernet_key = None
if env_key_path.exists():
    with open(env_key_path) as f:
        line = f.read().strip()
        if "=" in line:
            line = line.split("=", 1)[1].strip()
        fernet_key = line.encode()

if fernet_key:
    f = Fernet(fernet_key)
else:
    f = None

# --------------------------------------------------------------------------
# ✅ CORREÇÃO: Banco de Dados com fallbacks seguros
# --------------------------------------------------------------------------
DB_NAME = os.getenv("DB_NAME", "natura_inventory")
DB_USER = os.getenv("DB_USER", "natura_admin")  
DB_PASSWORD = os.getenv("DB_PASSWORD", "senha_segura_123")
DB_AI_USER = os.getenv("DB_AI_USER", DB_USER)  # ✅ Agora DB_USER sempre existe
DB_AI_PASSWORD = os.getenv("DB_AI_PASSWORD", DB_PASSWORD)
DB_HOST = os.getenv("DB_HOST", "localhost")
DB_PORT = os.getenv("DB_PORT", "5432")

# ✅ Configuração dinâmica de banco (PostgreSQL vs SQLite)
database_url = os.getenv("DATABASE_URL")
if database_url:
    # Produção: usa DATABASE_URL (Render, Heroku, etc)
    DATABASES = {
        "default": dj_database_url.parse(
            database_url,
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    # Desenvolvimento: PostgreSQL local ou SQLite
    if all([DB_NAME, DB_USER, DB_PASSWORD]):
        DATABASES = {
            "default": {
                "ENGINE": "django.db.backends.postgresql",
                "NAME": DB_NAME,
                "USER": DB_USER,
                "PASSWORD": DB_PASSWORD,
                "HOST": DB_HOST,
                "PORT": DB_PORT,
            }
        }
    else:
        # Fallback para SQLite se PostgreSQL não estiver configurado
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': BASE_DIR / 'db.sqlite3',
            }
        }

# ✅ DATABASE_URL para IA (LangChain/SQLAlchemy)
DATABASE_URL = f"postgresql+psycopg2://{quote_plus(DB_AI_USER)}:{quote_plus(DB_AI_PASSWORD)}@{DB_HOST}:{DB_PORT}/{DB_NAME}"

# --------------------------------------------------------------------------
# Segurança / Hosts
# --------------------------------------------------------------------------
SECRET_KEY = os.getenv("SECRET_KEY", "django-insecure-+rc4szhd0d(k@((%vp6og@k_p)y5x*$9_=214d4+p@e3^o4gj7")
DEBUG = os.getenv("DEBUG", "True").lower() == "true"

# ✅ ALLOWED_HOSTS dinâmico para vitrine
def get_allowed_hosts():
    """Configura hosts permitidos dinamicamente para vitrine"""
    hosts = ['localhost', '127.0.0.1', '0.0.0.0']
    
    # Produção
    main_domain = os.getenv("MAIN_DOMAIN", "gestao-estoque-one.vercel.app")
    hosts.extend([
        main_domain,
        f"www.{main_domain}",
        "gestao-estoque-k5vy.onrender.com",  # Render
        ".vercel.app",  # Qualquer deploy Vercel
        ".herokuapp.com",  # Heroku
    ])
    
    return hosts

ALLOWED_HOSTS = get_allowed_hosts()

# --------------------------------------------------------------------------
# JWT Configuration
# --------------------------------------------------------------------------
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1), 
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
}

# --------------------------------------------------------------------------
# Apps / Middleware
# --------------------------------------------------------------------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Libs adicionais
    'django_filters',
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    # Apps do projeto
    'inventory',
    'ai',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

# --------------------------------------------------------------------------
# ✅ CORS DINÂMICO para Vitrine
# --------------------------------------------------------------------------
def get_cors_allowed_origins():
    """Configura CORS dinamicamente para suportar vitrines por consultora"""
    origins = []
    
    # Desenvolvimento
    if DEBUG:
        origins.extend([
            "http://localhost:3000",
            "http://127.0.0.1:3000",
            "http://localhost:5173",
            "http://127.0.0.1:5173",
        ])
    
    # Produção
    main_domain = os.getenv("MAIN_DOMAIN", "gestao-estoque-one.vercel.app")
    origins.extend([
        f"https://{main_domain}",
        f"https://www.{main_domain}",
        "https://gestao-estoque-k5vy.onrender.com",
    ])
    
    return origins

CORS_ALLOWED_ORIGINS = get_cors_allowed_origins()

# ✅ CORS REGEX para qualquer slug de vitrine
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://.*\.vercel\.app$",  # Qualquer deploy Vercel
    r"^https://gestao-estoque.*\.vercel\.app$",  # Seus deploys específicos
    r"^http://localhost:\d+$",  # Desenvolvimento local
    r"^http://127\.0\.0\.1:\d+$",  # Desenvolvimento local
]

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = False

# CSRF para produção
CSRF_TRUSTED_ORIGINS = [
    "https://gestao-estoque-one.vercel.app",
    "https://gestao-estoque-k5vy.onrender.com",
]

SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin-allow-popups'

# --------------------------------------------------------------------------
# ✅ Cache para Vitrine (Performance)
# --------------------------------------------------------------------------
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
        'TIMEOUT': 300,  # 5 minutos
        'OPTIONS': {
            'MAX_ENTRIES': 1000,
        }
    }
}

# --------------------------------------------------------------------------
# Django REST Framework
# --------------------------------------------------------------------------
REST_FRAMEWORK = {
    "DEFAULT_FILTER_BACKENDS": ["django_filters.rest_framework.DjangoFilterBackend"],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_THROTTLE_CLASSES": [
        "rest_framework.throttling.AnonRateThrottle",
        "rest_framework.throttling.UserRateThrottle"
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "100/hour",  # Rate limit para vitrine pública
        "user": "1000/hour"
    }
}

# --------------------------------------------------------------------------
# User model
# --------------------------------------------------------------------------
AUTH_USER_MODEL = "inventory.CustomUser"

# --------------------------------------------------------------------------
# Validação de senhas
# --------------------------------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# --------------------------------------------------------------------------
# Internacionalização
# --------------------------------------------------------------------------
LANGUAGE_CODE = 'pt-br'
TIME_ZONE = 'America/Sao_Paulo'
USE_I18N = True
USE_TZ = True

# --------------------------------------------------------------------------
# Arquivos estáticos
# --------------------------------------------------------------------------
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# --------------------------------------------------------------------------
# ✅ Configurações específicas do projeto
# --------------------------------------------------------------------------
# Configurações da IA
AI_MODEL_NAME = os.getenv("AI_MODEL_NAME", "qwen:latest")
AI_TEMPERATURE = float(os.getenv("AI_TEMPERATURE", "0"))

# Configurações de upload
MAX_UPLOAD_SIZE = 5 * 1024 * 1024  # 5MB
ALLOWED_IMAGE_TYPES = ['image/jpeg', 'image/png', 'image/webp']

# Configurações de negócio
DEFAULT_CURRENCY = "BRL"
DEFAULT_LANGUAGE = "pt-BR"

# Configurações específicas para vitrine
STOREFRONT_CACHE_TIMEOUT = 300  # 5 minutos
STOREFRONT_MAX_ITEMS = 100      # Limite de produtos por vitrine

# --------------------------------------------------------------------------
# ✅ Firebase (mantendo sua configuração existente)
# --------------------------------------------------------------------------
try:
    import firebase_admin
    from firebase_admin import credentials
    
    firebase_json_str = os.environ.get("FIREBASE_CREDENTIALS")
    if firebase_json_str:
        try:
            firebase_creds_dict = json.loads(firebase_json_str)
            cred = credentials.Certificate(firebase_creds_dict)
            if not firebase_admin._apps:
                firebase_admin.initialize_app(cred)
                print("✅ Firebase Admin inicializado com sucesso.")
        except Exception as e:
            print(f"❌ Falha ao inicializar Firebase Admin: {e}")
    else:
        print("⚠️ Variável FIREBASE_CREDENTIALS não encontrada.")
except ImportError:
    print("⚠️ Firebase Admin SDK não instalado.")

print("✅ Settings carregado com sucesso!")
print(f"📊 DEBUG: {DEBUG}")
print(f"🗄️ Database: {DATABASES['default']['ENGINE']}")
print(f"🌐 CORS Origins: {len(CORS_ALLOWED_ORIGINS)} configurados")