name: Inventory Crawler 🕷️

on:
  schedule:
    # Roda todo dia às 03:00 AM (UTC)
    - cron: '0 3 * * *'
  workflow_dispatch: # Permite rodar manualmente clicando num botão

jobs:
  run-crawler:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout código
        uses: actions/checkout@v4

      - name: 🐍 Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 📦 Instalar Dependências
        run: |
          cd backend # 🚀 CORREÇÃO: Entra apenas na pasta 'backend' para achar o requirements.txt
          pip install -r requirements.txt
          pip install seleniumbase
          sbase install chromedriver  # Baixa driver do Chrome

      - name: 🚀 Rodar Crawler (Discovery + Enrichment)
        env:
            DATABASE_URL: ${{ secrets.DATABASE_URL }}
            SECRET_KEY: ${{ secrets.SECRET_KEY }}
            DEBUG: "False"
        run: |
          cd backend/core # Mantém a entrada no core aqui porque o manage.py está lá
          python manage.py crawl_all

      - name: ✅ Notificar Sucesso (Opcional)
        if: success()
        run: echo "Banco de dados atualizado com sucesso!"